eora default download years 1990-2022
IndEcol/pymrio pull request #118
Opened 2023-08-09 16:38 UTC by hazimhussein

changed eora default download years to include all years 1990 - 2022

2023-08-10 09:13 UTC, hazimhussein commented
Noticed that the latest years are not available for free, so I updated it to include only the years 1990 - 2016

2023-08-10 09:28 UTC, konstantinstadler requested changes
Can you please add exception when users request data from beyond the allowed time range. Eg. raise ValueError("Open data for Eora2017 only available until 2017") 
or something similar.

Probably also necessary to add in the docs

2023-08-10 09:54 UTC, hazimhussein commented
I added the exception and mentioned it in the docs, 
NB: I missed the title of the previous commit the available years  are 1990 - 2016 not 2017 the code was correct the commit title only was wrong

2023-08-15 11:19 UTC, konstantinstadler approved these changes

2023-08-15 11:19 UTC, merged